init_pipeline:
  steps:
    - { name: loader, component: directory_loader }
    - { name: chunk, component: recursive_chunker }
    - { name: index, component: [coarse_indexer], options: { coarse_indexer: { path: data/indices/coarse_index.json } } }

pipeline:
  steps:
    - { name: query_clean, component: query_cleaner }
    - { name: query_rewrite, component: query_rewriter }
    - { name: query_expand, component: multi_query_generator }
    - { name: retriever, component: coarse_retriever }
    - { name: rank_fusion, component: rank_fusion }
    - { name: rerank, component: embedding_ranker }
    - { name: prompt, component: prompt_builder, template_name: summarize.yaml, parser: Answer }
    - { name: generate, component: llm_generator }
    - { name: self_critic, component: self_critic }
    - { name: refine, component: refiner }
    - { name: parser, component: output_parser, parser: Answer }
